-- إسقاط roles.role_category — تصنيف ميّت يناقض نفسه ويعترض كلّ منصب جديد.
--
-- ═══ لماذا ═══
--
-- 1) يناقض council_type على معظم الصفوف (مقيس على الإنتاج 2026-07-15):
--      executive_council_president -> role_category='administrative_council'  (!)
--        رئيس المجلس التنفيذيّ مصنَّف إداريًّا، وهو الصفّ الوحيد بهذه القيمة.
--      department_head             -> role_category='committee'
--        منسّق القسم يقود قسمًا لا لجنة؛ والأقسام تحوي اللجان لا العكس.
--      hr_admin_member/qa_admin_member -> role_category='supreme_council'
--        مستوى 7 داخل إدارة، لا في المجلس الأعلى؛ وcouncil_type يقول 'administrative'.
--
-- 2) لا يقرؤه أحد:
--      - صفر دالّة في القاعدة تذكره.
--      - صفر مقارنة بقيمته في أي شيفرة (لا 'supreme_council' ولا سواها).
--      - auth-manager.js ينسخه إلى كائن ولا يستهلكه شيء (ويطلب roles(*) بالنجمة،
--        فلا يتأثّر بإسقاطه).
--      - فلتر boardMemberTypeFilter في dashboard.html واجهة ميّتة بلا JS،
--        وخياره 'executive_council' ليس قيمة يسمح بها القيد أصلًا.
--
-- 3) ومع ذلك NOT NULL — فكلّ منصب جديد يُجبَر على اختيار قيمة من تصنيف
--    لا معنى له متّسق. هذا ما أوقف تجربة إضافة منصب اليوم:
--      ERROR: null value in column "role_category" violates not-null constraint
--
-- ═══ البديل ═══
-- council_type (administrative|executive|both) + role_level (1..10) + is_elected
-- تصف الدور وصفًا كافيًا ومتّسقًا. لا حاجة إلى محور رابع يناقضها.
--
-- ═══ قبل تطبيقه على الإنتاج ═══
-- الموقع القديم يطلب العمود صراحةً في موضعين (لا يستعملان قيمته):
--   admin/js/results-analytics.js:1453
--   admin/js/surveys-manager.js:1698
-- إزالته من سلسلتَي select هناك شرطٌ سابق، وإلّا ردّ PostgREST خطأ 400.
-- أمّا هنا (السندبوكس/V2) فلا شيء يقرؤه.

alter table roles drop column if exists role_category;
